### PR TITLE
Fix composer uri

### PR DESCRIPTION
**Pull request by husanjun**

### CODE REVIEW

**Review by jfcherng — APPROVED** [review]

**Comment by jfcherng** [comment]
FYI, his URL comes from https://www.schemastore.org/json/

**Comment by husanjun** [comment]
> FYI, his URL comes from https://www.schemastore.org/json/

Thanks

**Comment by rchl** [comment]
Which means that it would be better if you'd run the update script instead - `./scripts/update_schemas.py`

**Comment by husanjun** [comment]
> Which means that it would be better if you'd run the update script instead - `./scripts/update_schemas.py`

Hi, @rchl  I've already run it, thanks

**Review by rchl — APPROVED** [review]

**Pull request merged**
